import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogoLeft } from "@/app/_components/LogoLeft";
import { LogoRight } from "@/app/_components/LogoRight";
import { Ring } from "@/app/_components/Ring";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Weather",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const rings = [280, 500, 800]; 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen overflow-hidden relative`}
      >

        <main className="relative z-10 w-full h-full">{children}</main>


        <div className="absolute inset-0 flex items-center justify-center z-30 pointer-events-none">

          {rings.map((size, index) => (
            <Ring key={index} size={size} />
          ))}


          <div className="relative z-40 flex gap-3 border border-gray-300 rounded-full p-4 bg-white dark:bg-black shadow-md">
            <LogoLeft />
            <LogoRight />
          </div>
        </div>
      </body>
    </html>
  );
}
